name:                pantomime
version:             0.1.0.0
github:              "PLSec-VU/pantomime"
license:             BSD-3-Clause
author:              "Robin Webbers"
maintainer:          "robin_webbers_1@hotmail.com"
copyright:           "2026 Robin Webbers"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/PLSec-VU/pantomime#readme>

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveGeneric
- DeriveDataTypeable
- DeriveTraversable
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- GADTs
- ImportQualifiedPost
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- RecursiveDo
# TODO: Perhaps it would be better to fade out any use of 'ScopedTypeVariables'
# in favor of only using 'TypeAbstractions'. It is a lot less cursed.
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeAbstractions
- TypeApplications
- TypeFamilies
- TypeOperators

dependencies:
- base >= 4.7 && < 5
- constraints >= 0.14.2
- grisette >= 0.13.0.0
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wprepositive-qualified-module

library:
  source-dirs: src
  dependencies:
  - ghc >= 9.12.2
  - primitive
  - composition
  - containers
  - unordered-containers
  - transformers
  - template-haskell
  - microlens
  - effectful-core >= 2.5.1.0
  - effectful
  - text
  - hashable
  - deepseq
  - bytestring
  - syb
  - data-fix
  - recursion-schemes

tests:
  pantomime-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pantomime
    - hspec
    - hspec-expectations
    - HUnit
    - ghc-paths
    - directory
    - silently
    - ghc
    - template-haskell
